# Generated by Django 6.0.5 on 2026-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proprietaire', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('titre_poste', models.CharField(max_length=150, verbose_name='Titre du poste')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('photo_profil', models.ImageField(upload_to='profil/', verbose_name='Photo de profil')),
                ('lien_github', models.URLField(blank=True, verbose_name='Lien GitHub')),
                ('lien_linkedin', models.URLField(blank=True, verbose_name='Lien LinkedIn')),
                ('lien_email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse email')),
            ],
            options={
                'verbose_name': 'Paramètres globaux',
                'verbose_name_plural': 'Paramètres globaux',
            },
        ),
    ]
