# Generated by Django 6.0.5 on 2026-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='lien_facebook',
            field=models.URLField(blank=True, verbose_name='Lien Facebook'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='lien_instagram',
            field=models.URLField(blank=True, verbose_name='Lien Instagram'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='lien_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro WhatsApp (avec indicatif, ex: +212600000000)'),
        ),
    ]
