# Generated by Django 6.0.5 on 2026-05-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('en_approfondissement', 'En approfondissement'), ('acquis', 'Acquis')], max_length=30, verbose_name='Statut')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules (ex: Python, Django, DRF)', max_length=300, verbose_name='Tags')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Auto-formation',
                'verbose_name_plural': 'Auto-formations',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='GroupeCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('icone', models.CharField(help_text="Nom de l'icône Bootstrap Icons (ex: globe2, phone, database)", max_length=60, verbose_name='Icône Bootstrap')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Groupe de compétences',
                'verbose_name_plural': 'Groupes de compétences',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200, verbose_name='Intitulé du module')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Module académique',
                'verbose_name_plural': 'Modules académiques',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='formation_description',
            field=models.TextField(blank=True, verbose_name='Formation — Description académique'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='formation_sous_titre',
            field=models.CharField(default='Algérie / Belgique', max_length=100, verbose_name='Formation — Sous-titre (ex: Algérie / Belgique)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='lien_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro WhatsApp'),
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('niveau', models.CharField(choices=[('strong', 'Maîtrisé'), ('normal', 'Connu'), ('learning', 'En apprentissage')], default='normal', max_length=20, verbose_name='Niveau')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='core.groupecompetence', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['ordre'],
            },
        ),
    ]
