# Generated by Django 6.0.5 on 2026-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_competences_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='hero_sous_titre',
            field=models.TextField(blank=True, help_text="Texte affiché sous le titre de poste dans la section d'accueil", verbose_name="Hero — Phrase d'accroche"),
        ),
    ]
