# Generated by Django 6.0.5 on 2026-05-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_hero_sous_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone'),
        ),
    ]
