# Generated by Django 6.0.5 on 2026-05-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='entreprise',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='objet',
            field=models.CharField(default='', max_length=200, verbose_name='Objet'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='prenom',
            field=models.CharField(default='', max_length=100, verbose_name='Prénom'),
        ),
    ]
