# Generated by Django 6.0.5 on 2026-05-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoformation',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='autoformation',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='autoformation',
            name='description_nl',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='autoformation',
            name='titre_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='autoformation',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='autoformation',
            name='titre_nl',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='competence',
            name='nom_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='competence',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='competence',
            name='nom_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='bio_fr',
            field=models.TextField(null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='bio_nl',
            field=models.TextField(null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='formation_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Formation — Description académique'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='formation_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Formation — Description académique'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='formation_description_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Formation — Description académique'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='formation_sous_titre_en',
            field=models.CharField(default='Algérie / Belgique', max_length=100, null=True, verbose_name='Formation — Sous-titre (ex: Algérie / Belgique)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='formation_sous_titre_fr',
            field=models.CharField(default='Algérie / Belgique', max_length=100, null=True, verbose_name='Formation — Sous-titre (ex: Algérie / Belgique)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='formation_sous_titre_nl',
            field=models.CharField(default='Algérie / Belgique', max_length=100, null=True, verbose_name='Formation — Sous-titre (ex: Algérie / Belgique)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='hero_sous_titre_en',
            field=models.TextField(blank=True, help_text="Texte affiché sous le titre de poste dans la section d'accueil", null=True, verbose_name="Hero — Phrase d'accroche"),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='hero_sous_titre_fr',
            field=models.TextField(blank=True, help_text="Texte affiché sous le titre de poste dans la section d'accueil", null=True, verbose_name="Hero — Phrase d'accroche"),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='hero_sous_titre_nl',
            field=models.TextField(blank=True, help_text="Texte affiché sous le titre de poste dans la section d'accueil", null=True, verbose_name="Hero — Phrase d'accroche"),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='titre_poste_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Titre du poste'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='titre_poste_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Titre du poste'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='titre_poste_nl',
            field=models.CharField(max_length=150, null=True, verbose_name='Titre du poste'),
        ),
        migrations.AddField(
            model_name='groupecompetence',
            name='nom_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du groupe'),
        ),
        migrations.AddField(
            model_name='groupecompetence',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du groupe'),
        ),
        migrations.AddField(
            model_name='groupecompetence',
            name='nom_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du groupe'),
        ),
        migrations.AddField(
            model_name='moduleacademique',
            name='texte_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Intitulé du module'),
        ),
        migrations.AddField(
            model_name='moduleacademique',
            name='texte_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Intitulé du module'),
        ),
        migrations.AddField(
            model_name='moduleacademique',
            name='texte_nl',
            field=models.CharField(max_length=200, null=True, verbose_name='Intitulé du module'),
        ),
    ]
