# Generated by Django 6.0.5 on 2026-05-09 14:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('categorie', models.CharField(choices=[('django', 'Django'), ('react_native', 'React Native')], max_length=20, verbose_name='Catégorie')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('defi_technique', models.TextField(verbose_name='Défi technique')),
                ('usage_ia', models.TextField(blank=True, verbose_name="Usage de l'IA")),
                ('image', models.ImageField(upload_to='projets/', verbose_name='Image du projet')),
                ('lien_github', models.URLField(blank=True, verbose_name='Lien GitHub')),
                ('date', models.DateField(verbose_name='Date de réalisation')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date'],
            },
        ),
    ]
