# Generated by Django 6.0.5 on 2026-05-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projets/videos/', verbose_name='Vidéo de démonstration'),
        ),
    ]
