# Generated by Django 6.0.5 on 2026-05-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_video_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lien_demo',
            field=models.URLField(blank=True, verbose_name='Lien démo (laisser vide si non déployé)'),
        ),
    ]
