# Generated by Django 6.0.5 on 2026-05-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_add_lien_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='usage_ia',
        ),
    ]
