# Generated by Django 6.0.5 on 2026-05-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_usage_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='defi_technique_en',
            field=models.TextField(null=True, verbose_name='Défi technique'),
        ),
        migrations.AddField(
            model_name='project',
            name='defi_technique_fr',
            field=models.TextField(null=True, verbose_name='Défi technique'),
        ),
        migrations.AddField(
            model_name='project',
            name='defi_technique_nl',
            field=models.TextField(null=True, verbose_name='Défi technique'),
        ),
        migrations.AddField(
            model_name='project',
            name='titre_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='project',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='project',
            name='titre_nl',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
    ]
