# Generated by Django 6.0.5 on 2026-06-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_defi_technique_en_project_defi_technique_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Stack technique')),
            ],
            options={
                'verbose_name': 'Stack technique',
                'verbose_name_plural': 'Stacks techniques',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='defi_technique',
        ),
        migrations.RemoveField(
            model_name='project',
            name='defi_technique_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='defi_technique_fr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='defi_technique_nl',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lien_demo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lien_github',
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(default='', upload_to='projets/videos/', verbose_name='Vidéo de démonstration (60s max)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='stacks',
            field=models.ManyToManyField(blank=True, related_name='projets', to='portfolio.stack', verbose_name='Stack technique'),
        ),
    ]
